---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: tobac
webhooks:
- name: tobac.nais.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
  clientConfig:
    #service:
      #namespace: nais
      #name: tobac
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1EZ3lNekE0TlRneE1Wb1hEVEk0TURneU1EQTROVGd4TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnpjCnRkdVBPaUh5YllxSWFXRHpkVk9yZUd1T1p3aTZKMDBlWDB3TXZhZlRrZVFrZElxM2MvV0ZDZHBySUZDV1lpbnAKN3NqMUFCZWREVmNzN1h6cVlNVmVtaFNHWENQMFVINFlPajNkQmlUR0RYSU1rTGRDMEIxV25NQ0ZRTmtCVE5QdQpQTGtVYzBkczRlR2g3MzhSM3lSYnhjMG1SUHBFZzlrcUV3V1YwU0p6NHh3U21XNDN3Mm8zN0xNeGE1MjFMNDJvCmZaNzQxWnpRSERDUFF3c01ndTUrSTh6T1RZNTBKQjZaM0VQUk1Da05nTzV0OGdTT242S0kweWswNTFpVWwyODgKcU13V0NyclZZRmhXMkYzTWNoYmYzTFFjVUZ6VzBUaFl6OXlrUDJ6L2MxOFVLVndzVXFobUxYZ0x1SnJEakdqVQpwbjJtWCttSE5WRGF6UWNxUitFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBZnpYL3Z1ZUxmcEh3N0F5Z09HV05EaEo4MW8KQnpxeFpBeHhCNHNvV2J5REZQcjByN1VmVGcvanU5SjVuZ09Hc2cyMWMrelpPK3MvQjhVblpkV2grTSs1K0FyaAo2NkpiSXpqMWJ6OVJIYTNkRnhLcC9NVlhqbVdIZGU0YmZhckcxSG8xOGUycVZCQ2hjNUtob2Vad25FdHpJd212ClgyNTZwVzFBWXhXMXpXM2IrWlVKeEhRMVYyeWdGL3pVQmFFT3JjSVNOeXh5bGh4UFN1clN6Z1JCVTR2dDdJVXkKYlY0V1Btbm0xRDAvYWVHVXcxakV3ZG0zWXVCVW9QNFFvYUs5WG9taHRkY2o5MmhQMGJST010dHNjbk1uTHQ1NApDdUJhamRaM2Voa2VnYURmcnBlWHl0c1BpOTJlZzhtck51RTlxUUFwYVVndGl2Z0toNS9sS3hBc2U3TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://your.laptop.fqdn:8443

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tobac
  namespace: nais
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tobac
    spec:
      containers:
      - image: navikt/tobac
        imagePullPolicy: Always
        name: tobac
        ports:
          - name: https
            containerPort: 8443
        volumeMounts:
        - mountPath: /cert
          name: tobac
      volumes:
      - configMap:
          name: tobac
        name: tobac

---
apiVersion: v1
kind: Service
metadata:
  name: tobac-int
  namespace: nais
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: tobac
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: tobac
  namespace: nais
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ExternalName
  externalName: your.laptop.fqdn
